// coverage:ignore-file
import 'package:omf_netflix/app/app.dart';
import 'package:omf_netflix/domain/domain.dart';

final List<TrendingReel> reels = [
  TrendingReel(
    'id1',
    'https://res.cloudinary.com/dv2lgyqm4/video/upload/v1629462477/user-posts/1629462474154.mp4',
    true,
    '40K',
    true,
  ),
  TrendingReel(
    'id2',
    'https://res.cloudinary.com/dv2lgyqm4/video/upload/v1637321160/user-posts/1637321076576.mp4',
    false,
    '82K',
    true,
  ),
  TrendingReel(
    'id3',
    'https://res.cloudinary.com/dv2lgyqm4/video/upload/v1629461766/user-posts/1629461755016.mp4',
    false,
    '3M',
    false,
  ),
  TrendingReel(
    'id4',
    'https://res.cloudinary.com/dv2lgyqm4/video/upload/v1637268758/user-posts/1637268732019.mp4',
    true,
    '800',
    false,
  ),
  TrendingReel(
    'id5',
    'https://res.cloudinary.com/dv2lgyqm4/video/upload/v1629461877/user-posts/1629461872888.mp4',
    true,
    '20K',
    false,
  ),
  TrendingReel(
    'id6',
    'https://res.cloudinary.com/dv2lgyqm4/video/upload/v1629461443/user-posts/1629461439436.mp4',
    false,
    '43K',
    true,
  ),
  TrendingReel(
    'id7',
    'https://res.cloudinary.com/dv2lgyqm4/video/upload/v1637321115/user-posts/1637321076567.mp4',
    true,
    '6M',
    false,
  ),
  TrendingReel(
    'id8',
    'https://res.cloudinary.com/dv2lgyqm4/video/upload/v1629462477/user-posts/1629462474154.mp4',
    false,
    '48K',
    true,
  ),
  TrendingReel(
    'id9',
    'https://res.cloudinary.com/dv2lgyqm4/video/upload/v1637321160/user-posts/1637321076576.mp4',
    true,
    '234',
    true,
  ),
  TrendingReel(
    'id10',
    'https://res.cloudinary.com/dv2lgyqm4/video/upload/v1637321160/user-posts/1637321076576.mp4',
    true,
    '48K',
    false,
  ),
];

final List<MoviesCategory> moviesCategoryList = [
  MoviesCategory(
    id: 1,
    categoryName: StringConstants.recentlyAdded,
    movieCategoryType: MovieCategoryType.movie,
    subCategory: moviesSubCategoryList,
  ),
  MoviesCategory(
    id: 2,
    categoryName: StringConstants.newEpisodes,
    movieCategoryType: MovieCategoryType.movie,
    subCategory: moviesSubCategoryList,
  ),
  MoviesCategory(
    id: 3,
    categoryName: StringConstants.trendingNow,
    movieCategoryType: MovieCategoryType.movie,
    subCategory: moviesSubCategoryList,
  ),
  MoviesCategory(
    id: 4,
    categoryName: StringConstants.omfSeries,
    movieCategoryType: MovieCategoryType.omfseries,
    subCategory: moviesSubCategoryList,
  ),
  MoviesCategory(
    id: 5,
    categoryName: StringConstants.blockbusterMovies,
    movieCategoryType: MovieCategoryType.movie,
    subCategory: moviesSubCategoryList,
  ),
  MoviesCategory(
    id: 6,
    categoryName: StringConstants.continueWatching,
    movieCategoryType: MovieCategoryType.continues,
    subCategory: moviesSubCategoryList,
  ),
];

final List<MoviesSubCategory> moviesSubCategoryList = [
  MoviesSubCategory(
    id: 1,
    videoName: AssetConstants.movie1,
    videoUrl: AssetConstants.movie1,
    indices: [],
    startIndex: 0,
    endIndex: 0,
  ),
  MoviesSubCategory(
    id: 2,
    videoName: AssetConstants.movie2,
    videoUrl: AssetConstants.movie2,
    indices: [],
    startIndex: 0,
    endIndex: 0,
  ),
  MoviesSubCategory(
    id: 3,
    videoName: AssetConstants.movie3,
    videoUrl: AssetConstants.movie3,
    indices: [],
    startIndex: 0,
    endIndex: 0,
  ),
  MoviesSubCategory(
    id: 4,
    videoName: AssetConstants.movie4,
    videoUrl: AssetConstants.movie4,
    indices: [],
    startIndex: 0,
    endIndex: 0,
  ),
  MoviesSubCategory(
    id: 5,
    videoName: AssetConstants.movie5,
    videoUrl: AssetConstants.movie5,
    indices: [],
    startIndex: 0,
    endIndex: 0,
  ),
  MoviesSubCategory(
    id: 6,
    videoName: AssetConstants.movie6,
    videoUrl: AssetConstants.movie6,
    indices: [],
    startIndex: 0,
    endIndex: 0,
  ),
  MoviesSubCategory(
    id: 7,
    videoName: AssetConstants.movie7,
    videoUrl: AssetConstants.movie7,
    indices: [],
    startIndex: 0,
    endIndex: 0,
  ),
  MoviesSubCategory(
    id: 8,
    videoName: AssetConstants.movie8,
    videoUrl: AssetConstants.movie8,
    indices: [],
    startIndex: 0,
    endIndex: 0,
  ),
  MoviesSubCategory(
    id: 9,
    videoName: AssetConstants.movie1,
    videoUrl: AssetConstants.movie1,
    indices: [],
    startIndex: 0,
    endIndex: 0,
  ),
  MoviesSubCategory(
    id: 10,
    videoName: AssetConstants.movie2,
    videoUrl: AssetConstants.movie2,
    indices: [],
    startIndex: 0,
    endIndex: 0,
  ),
  MoviesSubCategory(
    id: 11,
    videoName: AssetConstants.movie3,
    videoUrl: AssetConstants.movie3,
    indices: [],
    startIndex: 0,
    endIndex: 0,
  ),
  MoviesSubCategory(
    id: 12,
    videoName: AssetConstants.movie4,
    videoUrl: AssetConstants.movie4,
    indices: [],
    startIndex: 0,
    endIndex: 0,
  ),
];
